/**
 * SAMPLE / DEVELOPMENT TRADE VALUES ONLY (internal).
 * Public UI does not show sample badges or the development banner.
 * Prices remain estimates until staff review and approval in admin.
 */
import type { TradeItem, TradeSettings } from "@/lib/trade/types";

export const SAMPLE_DATA_WARNING =
  "SAMPLE DEVELOPMENT DATA — These estimated values are placeholders for website development and are not official PixelNation trade offers. Review and replace before launch.";

export const DEFAULT_TRADE_SETTINGS: TradeSettings = {
  storeCreditMultiplier: 1.2,
  showSampleDataBanner: false,
  publishSampleItems: true,
};

function sampleItem(
  partial: Omit<TradeItem, "createdAt" | "updatedAt" | "isSample" | "active"> & {
    createdAt?: string;
    updatedAt?: string;
  },
): TradeItem {
  const now = "2026-08-01T12:00:00.000Z";
  return {
    ...partial,
    isSample: true,
    active: true,
    createdAt: partial.createdAt ?? now,
    updatedAt: partial.updatedAt ?? now,
  };
}

export const SAMPLE_TRADE_ITEMS: TradeItem[] = [
  sampleItem({
    id: "sample-ps5-disc",
    slug: "playstation-5-disc-edition",
    name: "PlayStation 5 Disc Edition",
    brand: "Sony",
    category: "PlayStation",
    model: "CFI-1215A",
    storage: "825GB",
    imageUrl: "/images/trade-values/ps5-disc.webp",
    cashValueCents: 18500,
    storeCreditValueCents: 22500,
    requiredAccessories: "Power cable, HDMI cable, DualSense controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 10,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE — replace with approved value",
  }),
  sampleItem({
    id: "sample-ps5-digital",
    slug: "playstation-5-digital-edition",
    name: "PlayStation 5 Digital Edition",
    brand: "Sony",
    category: "PlayStation",
    model: "CFI-1215B",
    storage: "825GB",
    imageUrl: "/images/trade-values/ps5-digital.webp",
    cashValueCents: 16000,
    storeCreditValueCents: 19500,
    requiredAccessories: "Power cable, HDMI cable, DualSense controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 20,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-xbox-series-x",
    slug: "xbox-series-x",
    name: "Xbox Series X",
    brand: "Microsoft",
    category: "Xbox",
    model: "Series X",
    storage: "1TB",
    imageUrl: "/images/trade-values/xbox-series-x.webp",
    cashValueCents: 17500,
    storeCreditValueCents: 21000,
    requiredAccessories: "Power cable, HDMI cable, Xbox controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 30,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-xbox-series-s",
    slug: "xbox-series-s",
    name: "Xbox Series S",
    brand: "Microsoft",
    category: "Xbox",
    model: "Series S",
    storage: "512GB",
    imageUrl: "/images/trade-values/xbox-series-s.webp",
    cashValueCents: 11000,
    storeCreditValueCents: 13500,
    requiredAccessories: "Power cable, HDMI cable, Xbox controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 35,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-switch-oled",
    slug: "nintendo-switch-oled",
    name: "Nintendo Switch OLED",
    brand: "Nintendo",
    category: "Nintendo",
    model: "HEG-001",
    storage: "64GB",
    imageUrl: "/images/trade-values/nintendo-switch-oled.webp",
    cashValueCents: 14000,
    storeCreditValueCents: 17000,
    requiredAccessories: "Joy-Con pair, dock, AC adapter, Joy-Con grip (if included originally)",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 40,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-switch-v2",
    slug: "nintendo-switch-v2",
    name: "Nintendo Switch (V2)",
    brand: "Nintendo",
    category: "Nintendo",
    model: "HAC-001(-01)",
    storage: "32GB",
    imageUrl: "/images/trade-values/nintendo-switch-v2.webp",
    cashValueCents: 11000,
    storeCreditValueCents: 13500,
    requiredAccessories: "Joy-Con pair, dock, AC adapter",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 45,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE — revised Switch model (improved battery)",
  }),
  sampleItem({
    id: "sample-switch-lite",
    slug: "nintendo-switch-lite",
    name: "Nintendo Switch Lite",
    brand: "Nintendo",
    category: "Nintendo",
    model: "HDH-001",
    storage: "32GB",
    imageUrl: "/images/trade-values/nintendo-switch-lite-blue.webp",
    cashValueCents: 7000,
    storeCreditValueCents: 8500,
    requiredAccessories: "USB-C charger",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 50,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-steam-deck-oled",
    slug: "steam-deck-oled-512gb",
    name: "Steam Deck OLED 512GB",
    brand: "Valve",
    category: "Gaming Handhelds",
    model: "Steam Deck OLED",
    storage: "512GB",
    imageUrl: "/images/trade-values/steam-deck-oled.webp",
    cashValueCents: 24000,
    storeCreditValueCents: 29000,
    requiredAccessories: "USB-C charger",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 55,
    repairHref: null,
    internalNotes: "SAMPLE — Valve OLED press kit product photo",
  }),
  sampleItem({
    id: "sample-steam-deck-512",
    slug: "steam-deck-512gb",
    name: "Steam Deck LCD 512GB",
    brand: "Valve",
    category: "Gaming Handhelds",
    model: "Steam Deck LCD",
    storage: "512GB",
    imageUrl: "/images/trade-values/steam-deck-lcd.webp",
    cashValueCents: 18000,
    storeCreditValueCents: 22000,
    requiredAccessories: "USB-C charger",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 60,
    repairHref: null,
    internalNotes: "SAMPLE — LCD model",
  }),
  sampleItem({
    id: "sample-rog-ally",
    slug: "asus-rog-ally",
    name: "ASUS ROG Ally",
    brand: "ASUS",
    category: "Gaming Handhelds",
    model: "RC71L",
    storage: "512GB",
    imageUrl: "/images/trade-values/rog-ally.webp",
    cashValueCents: 22000,
    storeCreditValueCents: 26500,
    requiredAccessories: "USB-C charger",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 65,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-playstation-portal",
    slug: "playstation-portal",
    name: "PlayStation Portal",
    brand: "Sony",
    category: "Gaming Handhelds",
    model: "PlayStation Portal Remote Player",
    storage: "",
    imageUrl: "/images/trade-values/playstation-portal.webp",
    cashValueCents: 9000,
    storeCreditValueCents: 11000,
    requiredAccessories: "USB-C charger",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 68,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-dualsense",
    slug: "dualsense-wireless-controller",
    name: "DualSense Wireless Controller",
    brand: "Sony",
    category: "Controllers & Accessories",
    model: "DualSense",
    storage: "",
    imageUrl: "/images/trade-values/dualsense-controller.webp",
    cashValueCents: 2000,
    storeCreditValueCents: 2500,
    requiredAccessories: "USB-C cable preferred",
    conditionNote: "Fully functional sticks, buttons, and charging",
    acceptsNonworking: true,
    nonworkingNote: "Drift and charging issues may still receive an offer after evaluation.",
    featured: false,
    sortOrder: 70,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-ps4-pro",
    slug: "playstation-4-pro",
    name: "PlayStation 4 Pro",
    brand: "Sony",
    category: "PlayStation",
    model: "CUH-70xx",
    storage: "1TB",
    imageUrl: "/images/trade-values/ps4-pro.webp",
    cashValueCents: 9000,
    storeCreditValueCents: 11000,
    requiredAccessories: "Power cable, HDMI cable, DualShock 4 controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 80,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-ps4-slim",
    slug: "playstation-4-slim",
    name: "PlayStation 4 Slim",
    brand: "Sony",
    category: "PlayStation",
    model: "CUH-20xx",
    storage: "500GB / 1TB",
    imageUrl: "/images/trade-values/ps4-slim.webp",
    cashValueCents: 7000,
    storeCreditValueCents: 8500,
    requiredAccessories: "Power cable, HDMI cable, DualShock 4 controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 85,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-xbox-one-x",
    slug: "xbox-one-x",
    name: "Xbox One X",
    brand: "Microsoft",
    category: "Xbox",
    model: "One X",
    storage: "1TB",
    imageUrl: "/images/trade-values/xbox-one-x.webp",
    cashValueCents: 8000,
    storeCreditValueCents: 10000,
    requiredAccessories: "Power brick, HDMI cable, Xbox controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 88,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-xbox-one-s",
    slug: "xbox-one-s",
    name: "Xbox One S",
    brand: "Microsoft",
    category: "Xbox",
    model: "One S",
    storage: "500GB / 1TB",
    imageUrl: "/images/trade-values/xbox-one-s.webp",
    cashValueCents: 5500,
    storeCreditValueCents: 7000,
    requiredAccessories: "Power cable, HDMI cable, Xbox controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 90,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-n64",
    slug: "nintendo-64-console",
    name: "Nintendo 64 Console",
    brand: "Nintendo",
    category: "Retro Gaming",
    model: "NUS-001",
    storage: "",
    imageUrl: "/images/trade-values/nintendo-64.webp",
    cashValueCents: 4500,
    storeCreditValueCents: 5500,
    requiredAccessories: "Power supply, AV/RF cable, at least one controller",
    conditionNote: "Powers on and plays games; normal age-related wear expected",
    acceptsNonworking: true,
    nonworkingNote: "Nonworking retro systems may still be evaluated.",
    featured: false,
    sortOrder: 100,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-meta-quest-3",
    slug: "meta-quest-3",
    name: "Meta Quest 3",
    brand: "Meta",
    category: "Virtual Reality",
    model: "Quest 3",
    storage: "128GB / 512GB",
    imageUrl: "/images/trade-values/meta-quest-3.webp",
    cashValueCents: 17000,
    storeCreditValueCents: 20500,
    requiredAccessories: "Headset, charging cable, Touch Plus controllers",
    conditionNote: "Fully functional tracking and displays",
    acceptsNonworking: true,
    nonworkingNote: "Nonworking VR kits may still be evaluated.",
    featured: false,
    sortOrder: 105,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-iphone-12",
    slug: "apple-iphone-12-64gb",
    name: "Apple iPhone 12 64GB",
    brand: "Apple",
    category: "Phones",
    model: "iPhone 12",
    storage: "64GB",
    imageUrl: "/images/trade-values/iphone-12.webp",
    cashValueCents: 8000,
    storeCreditValueCents: null,
    requiredAccessories: "Device only; charger optional",
    conditionNote: "Fully functional, Face ID working, not activation locked",
    acceptsNonworking: true,
    nonworkingNote: "Broken phones may still receive an offer because PixelNation repairs electronics.",
    featured: false,
    sortOrder: 110,
    repairHref: "/phone-repair",
    internalNotes: "SAMPLE — credit uses multiplier when null",
  }),
  sampleItem({
    id: "sample-ipad-9",
    slug: "apple-ipad-9th-gen-64gb",
    name: "Apple iPad 9th Gen 64GB",
    brand: "Apple",
    category: "Tablets",
    model: "iPad 9th generation",
    storage: "64GB",
    imageUrl: "/images/trade-values/ipad-9th-gen.webp",
    cashValueCents: 9000,
    storeCreditValueCents: 11000,
    requiredAccessories: "Device; charger preferred",
    conditionNote: "Fully functional and not account locked",
    acceptsNonworking: true,
    nonworkingNote: "Damaged tablets may still be evaluated.",
    featured: false,
    sortOrder: 120,
    repairHref: "/phone-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-laptop",
    slug: "windows-laptop-generic-i5",
    name: "Windows Laptop (Intel i5 / 8GB / 256GB)",
    brand: "Various",
    category: "Computers",
    model: "Mid-range Windows laptop",
    storage: "256GB SSD",
    imageUrl: "/images/trade-values/windows-laptop.webp",
    cashValueCents: 7500,
    storeCreditValueCents: 9500,
    requiredAccessories: "Charger required",
    conditionNote: "Boots to OS, keyboard and display functional",
    acceptsNonworking: true,
    nonworkingNote: "Nonworking computers may still receive a parts or repair-based offer.",
    featured: false,
    sortOrder: 130,
    repairHref: "/computer-repair",
    internalNotes: "SAMPLE — generic placeholder SKU",
  }),
  sampleItem({
    id: "sample-psvr2",
    slug: "playstation-vr2",
    name: "PlayStation VR2",
    brand: "Sony",
    category: "Virtual Reality",
    model: "PSVR2",
    storage: "",
    imageUrl: "/images/trade-values/psvr2.webp",
    cashValueCents: 15000,
    storeCreditValueCents: 18500,
    requiredAccessories: "Headset, processors/cables, Sense controllers",
    conditionNote: "Fully functional tracking and displays",
    acceptsNonworking: false,
    nonworkingNote: "Nonworking VR kits require individual evaluation and may be declined.",
    featured: false,
    sortOrder: 140,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-other-router",
    slug: "consumer-wifi-router",
    name: "Consumer Wi-Fi Router",
    brand: "Various",
    category: "Other Electronics",
    model: "Standard dual-band router",
    storage: "",
    imageUrl: "/images/trade-values/wifi-router.webp",
    cashValueCents: 1500,
    storeCreditValueCents: 2000,
    requiredAccessories: "Power adapter",
    conditionNote: "Powers on and broadcasts a network",
    acceptsNonworking: false,
    nonworkingNote: "Nonworking routers are usually declined.",
    featured: false,
    sortOrder: 150,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
];
