import type { TradeItem, TradeSettings } from "@/lib/trade/types";

/**
 * SAMPLE / DEVELOPMENT TRADE VALUES ONLY.
 * Do not present these as real PixelNation offers until staff review and approval.
 */
export const SAMPLE_DATA_WARNING =
  "SAMPLE DEVELOPMENT DATA — These estimated values are placeholders for website development and are not official PixelNation trade offers. Review and replace before launch.";

export const DEFAULT_TRADE_SETTINGS: TradeSettings = {
  storeCreditMultiplier: 1.2,
  showSampleDataBanner: true,
  publishSampleItems: true,
};

function sampleItem(
  partial: Omit<TradeItem, "createdAt" | "updatedAt" | "isSample" | "active"> & {
    createdAt?: string;
    updatedAt?: string;
  },
): TradeItem {
  const now = "2026-08-01T12:00:00.000Z";
  return {
    ...partial,
    isSample: true,
    active: true,
    createdAt: partial.createdAt ?? now,
    updatedAt: partial.updatedAt ?? now,
  };
}

export const SAMPLE_TRADE_ITEMS: TradeItem[] = [
  sampleItem({
    id: "sample-ps5-disc",
    slug: "playstation-5-disc-edition",
    name: "PlayStation 5 Disc Edition",
    brand: "Sony",
    category: "PlayStation",
    model: "CFI-1215A",
    storage: "825GB",
    imageUrl: "/images/ps5hdmiport.png",
    cashValueCents: 18500,
    storeCreditValueCents: 22500,
    requiredAccessories: "Power cable, HDMI cable, DualSense controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 10,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE — replace with approved value",
  }),
  sampleItem({
    id: "sample-ps5-digital",
    slug: "playstation-5-digital-edition",
    name: "PlayStation 5 Digital Edition",
    brand: "Sony",
    category: "PlayStation",
    model: "CFI-1215B",
    storage: "825GB",
    imageUrl: "/images/ps5hdmiport.png",
    cashValueCents: 16000,
    storeCreditValueCents: 19500,
    requiredAccessories: "Power cable, HDMI cable, DualSense controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 20,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-xbox-series-x",
    slug: "xbox-series-x",
    name: "Xbox Series X",
    brand: "Microsoft",
    category: "Xbox",
    model: "Series X",
    storage: "1TB",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 17500,
    storeCreditValueCents: 21000,
    requiredAccessories: "Power cable, HDMI cable, Xbox controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 30,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-switch-oled",
    slug: "nintendo-switch-oled",
    name: "Nintendo Switch OLED",
    brand: "Nintendo",
    category: "Nintendo",
    model: "HEG-001",
    storage: "64GB",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 14000,
    storeCreditValueCents: 17000,
    requiredAccessories: "Joy-Con pair, dock, AC adapter, Joy-Con grip (if included originally)",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: true,
    sortOrder: 40,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-switch-lite",
    slug: "nintendo-switch-lite",
    name: "Nintendo Switch Lite",
    brand: "Nintendo",
    category: "Nintendo",
    model: "HDH-001",
    storage: "32GB",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 7000,
    storeCreditValueCents: 8500,
    requiredAccessories: "USB-C charger",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 50,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-steam-deck-512",
    slug: "steam-deck-512gb",
    name: "Steam Deck 512GB",
    brand: "Valve",
    category: "Gaming Handhelds",
    model: "Steam Deck LCD",
    storage: "512GB",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 18000,
    storeCreditValueCents: 22000,
    requiredAccessories: "USB-C charger",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 60,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-dualsense",
    slug: "dualsense-wireless-controller",
    name: "DualSense Wireless Controller",
    brand: "Sony",
    category: "Controllers & Accessories",
    model: "DualSense",
    storage: "",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 2000,
    storeCreditValueCents: 2500,
    requiredAccessories: "USB-C cable preferred",
    conditionNote: "Fully functional sticks, buttons, and charging",
    acceptsNonworking: true,
    nonworkingNote: "Drift and charging issues may still receive an offer after evaluation.",
    featured: false,
    sortOrder: 70,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-ps4-pro",
    slug: "playstation-4-pro",
    name: "PlayStation 4 Pro",
    brand: "Sony",
    category: "PlayStation",
    model: "CUH-70xx",
    storage: "1TB",
    imageUrl: "/images/ps5hdmiport.png",
    cashValueCents: 9000,
    storeCreditValueCents: 11000,
    requiredAccessories: "Power cable, HDMI cable, DualShock 4 controller",
    conditionNote: "Fully functional and in good cosmetic condition",
    acceptsNonworking: true,
    nonworkingNote: "PixelNation may still make an offer after inspection.",
    featured: false,
    sortOrder: 80,
    repairHref: "/console-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-n64",
    slug: "nintendo-64-console",
    name: "Nintendo 64 Console",
    brand: "Nintendo",
    category: "Retro Gaming",
    model: "NUS-001",
    storage: "",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 4500,
    storeCreditValueCents: 5500,
    requiredAccessories: "Power supply, AV/RF cable, at least one controller",
    conditionNote: "Powers on and plays games; normal age-related wear expected",
    acceptsNonworking: true,
    nonworkingNote: "Nonworking retro systems may still be evaluated.",
    featured: false,
    sortOrder: 90,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-iphone-12",
    slug: "apple-iphone-12-64gb",
    name: "Apple iPhone 12 64GB",
    brand: "Apple",
    category: "Phones",
    model: "iPhone 12",
    storage: "64GB",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 8000,
    storeCreditValueCents: null,
    requiredAccessories: "Device only; charger optional",
    conditionNote: "Fully functional, Face ID working, not activation locked",
    acceptsNonworking: true,
    nonworkingNote: "Broken phones may still receive an offer because PixelNation repairs electronics.",
    featured: false,
    sortOrder: 100,
    repairHref: "/phone-repair",
    internalNotes: "SAMPLE — credit uses multiplier when null",
  }),
  sampleItem({
    id: "sample-ipad-9",
    slug: "apple-ipad-9th-gen-64gb",
    name: "Apple iPad 9th Gen 64GB",
    brand: "Apple",
    category: "Tablets",
    model: "iPad 9th generation",
    storage: "64GB",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 9000,
    storeCreditValueCents: 11000,
    requiredAccessories: "Device; charger preferred",
    conditionNote: "Fully functional and not account locked",
    acceptsNonworking: true,
    nonworkingNote: "Damaged tablets may still be evaluated.",
    featured: false,
    sortOrder: 110,
    repairHref: "/phone-repair",
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-laptop",
    slug: "windows-laptop-generic-i5",
    name: "Windows Laptop (Intel i5 / 8GB / 256GB)",
    brand: "Various",
    category: "Computers",
    model: "Mid-range Windows laptop",
    storage: "256GB SSD",
    imageUrl: "/images/laptopdisplay.png",
    cashValueCents: 7500,
    storeCreditValueCents: 9500,
    requiredAccessories: "Charger required",
    conditionNote: "Boots to OS, keyboard and display functional",
    acceptsNonworking: true,
    nonworkingNote: "Nonworking computers may still receive a parts or repair-based offer.",
    featured: false,
    sortOrder: 120,
    repairHref: "/computer-repair",
    internalNotes: "SAMPLE — generic placeholder SKU",
  }),
  sampleItem({
    id: "sample-psvr2",
    slug: "playstation-vr2",
    name: "PlayStation VR2",
    brand: "Sony",
    category: "Virtual Reality",
    model: "PSVR2",
    storage: "",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 15000,
    storeCreditValueCents: 18500,
    requiredAccessories: "Headset, processors/cables, Sense controllers",
    conditionNote: "Fully functional tracking and displays",
    acceptsNonworking: false,
    nonworkingNote: "Nonworking VR kits require individual evaluation and may be declined.",
    featured: false,
    sortOrder: 130,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
  sampleItem({
    id: "sample-other-router",
    slug: "consumer-wifi-router",
    name: "Consumer Wi-Fi Router",
    brand: "Various",
    category: "Other Electronics",
    model: "Standard dual-band router",
    storage: "",
    imageUrl: "/images/pixellogo.png",
    cashValueCents: 1500,
    storeCreditValueCents: 2000,
    requiredAccessories: "Power adapter",
    conditionNote: "Powers on and broadcasts a network",
    acceptsNonworking: false,
    nonworkingNote: "Nonworking routers are usually declined.",
    featured: false,
    sortOrder: 140,
    repairHref: null,
    internalNotes: "SAMPLE",
  }),
];
